var annotated_dup =
[
    [ "MCP", "namespace_m_c_p.html", [
      [ "NBT", "namespace_m_c_p_1_1_n_b_t.html", [
        [ "Tag", "class_m_c_p_1_1_n_b_t_1_1_tag.html", "class_m_c_p_1_1_n_b_t_1_1_tag" ]
      ] ],
      [ "BlockUpdatePacket", "class_m_c_p_1_1_block_update_packet.html", "class_m_c_p_1_1_block_update_packet" ],
      [ "CenterChunkPacket", "class_m_c_p_1_1_center_chunk_packet.html", "class_m_c_p_1_1_center_chunk_packet" ],
      [ "ChunkDataPacket", "class_m_c_p_1_1_chunk_data_packet.html", "class_m_c_p_1_1_chunk_data_packet" ],
      [ "ConfirmTeleportPacket", "class_m_c_p_1_1_confirm_teleport_packet.html", "class_m_c_p_1_1_confirm_teleport_packet" ],
      [ "HandshakePacket", "class_m_c_p_1_1_handshake_packet.html", "class_m_c_p_1_1_handshake_packet" ],
      [ "KeepAlivePacket", "class_m_c_p_1_1_keep_alive_packet.html", "class_m_c_p_1_1_keep_alive_packet" ],
      [ "LoginStartPacket", "class_m_c_p_1_1_login_start_packet.html", "class_m_c_p_1_1_login_start_packet" ],
      [ "LoginSuccessPacket", "class_m_c_p_1_1_login_success_packet.html", "class_m_c_p_1_1_login_success_packet" ],
      [ "Packet", "class_m_c_p_1_1_packet.html", "class_m_c_p_1_1_packet" ],
      [ "PlayerActionPacket", "class_m_c_p_1_1_player_action_packet.html", "class_m_c_p_1_1_player_action_packet" ],
      [ "PlayerInfoPacket", "class_m_c_p_1_1_player_info_packet.html", "class_m_c_p_1_1_player_info_packet" ],
      [ "Property", "struct_m_c_p_1_1_property.html", "struct_m_c_p_1_1_property" ],
      [ "RemoveEntitiesPacket", "class_m_c_p_1_1_remove_entities_packet.html", "class_m_c_p_1_1_remove_entities_packet" ],
      [ "SetCreativeModeSlotPacket", "class_m_c_p_1_1_set_creative_mode_slot_packet.html", "class_m_c_p_1_1_set_creative_mode_slot_packet" ],
      [ "SetEntityVelocityPacket", "class_m_c_p_1_1_set_entity_velocity_packet.html", "class_m_c_p_1_1_set_entity_velocity_packet" ],
      [ "SetHeldItemPacket", "class_m_c_p_1_1_set_held_item_packet.html", "class_m_c_p_1_1_set_held_item_packet" ],
      [ "SetPlayerPositionAndRotation", "class_m_c_p_1_1_set_player_position_and_rotation.html", "class_m_c_p_1_1_set_player_position_and_rotation" ],
      [ "SpawnEntityPacket", "class_m_c_p_1_1_spawn_entity_packet.html", "class_m_c_p_1_1_spawn_entity_packet" ],
      [ "SpawnPlayerPacket", "class_m_c_p_1_1_spawn_player_packet.html", "class_m_c_p_1_1_spawn_player_packet" ],
      [ "SynchronizePlayerPositionPacket", "class_m_c_p_1_1_synchronize_player_position_packet.html", "class_m_c_p_1_1_synchronize_player_position_packet" ],
      [ "UpdateEntityPositionAndRotationPacket", "class_m_c_p_1_1_update_entity_position_and_rotation_packet.html", "class_m_c_p_1_1_update_entity_position_and_rotation_packet" ],
      [ "UpdateEntityPositionPacket", "class_m_c_p_1_1_update_entity_position_packet.html", "class_m_c_p_1_1_update_entity_position_packet" ],
      [ "UpdateEntityRotationPacket", "class_m_c_p_1_1_update_entity_rotation_packet.html", "class_m_c_p_1_1_update_entity_rotation_packet" ],
      [ "UseItemOnPacket", "class_m_c_p_1_1_use_item_on_packet.html", "class_m_c_p_1_1_use_item_on_packet" ],
      [ "Uuid", "class_m_c_p_1_1_uuid.html", "class_m_c_p_1_1_uuid" ],
      [ "VarInt", "class_m_c_p_1_1_var_int.html", "class_m_c_p_1_1_var_int" ]
    ] ],
    [ "Block", "struct_block.html", "struct_block" ],
    [ "BlockState", "class_block_state.html", "class_block_state" ],
    [ "CameraData", "struct_camera_data.html", "struct_camera_data" ],
    [ "Chunk", "class_chunk.html", "class_chunk" ],
    [ "Collidable", "class_collidable.html", "class_collidable" ],
    [ "Engine", "class_engine.html", "class_engine" ],
    [ "Entity", "class_entity.html", "class_entity" ],
    [ "EntityComponent", "class_entity_component.html", "class_entity_component" ],
    [ "GameViewController", "interface_game_view_controller.html", "interface_game_view_controller" ],
    [ "InstanceData", "struct_instance_data.html", "struct_instance_data" ],
    [ "MobEntity", "class_mob_entity.html", "class_mob_entity" ],
    [ "PhysicsConformable", "class_physics_conformable.html", "class_physics_conformable" ],
    [ "Renderer", "class_renderer.html", "class_renderer" ],
    [ "Streamable", "class_streamable.html", "class_streamable" ],
    [ "TCPClient", "class_t_c_p_client.html", "class_t_c_p_client" ],
    [ "TCPStream", "class_t_c_p_stream.html", "class_t_c_p_stream" ],
    [ "TextureAtlas", "class_texture_atlas.html", "class_texture_atlas" ],
    [ "Tuple3DHash", "struct_tuple3_d_hash.html", "struct_tuple3_d_hash" ],
    [ "Vertex", "struct_vertex.html", "struct_vertex" ],
    [ "World", "class_world.html", "class_world" ]
];